### ISSUE TITLE
HTTP error code when normal page not found

### ISSUE THREAD

**Issue by nwoh122** [RiccaAtAlicia/AliciaTlsTransport#2]
In [README](https://github.com/RiccaAtAlicia/AliciaTlsTransport/blob/master/README.md)
> Those who access your server without proper key will get a normal page ( or a 403 for not existing pages)

Should it return a 404 error code of Not Found?

**Comment by RiccaAtAlicia** [comment]
I think 403 is more secure,for frequently asking for a non-existing page is suspectable
